### ISSUE TITLE
Fabric Support (JSON Entity conversion)

### ISSUE THREAD

**Issue by darkfrog26** [http4s/http4s-fabric#1]
I know the plan in the long-run is to migrate a lot of these support packages out of `http4s` into their own repos, but I'd like to get Fabric (https://github.com/outr/fabric) entity support added as a module. It's a very simple implementation:

```scala
import cats.MonadThrow
import cats.data.EitherT
import cats.effect.IO
import cats.implicits.catsSyntaxEitherId
import fabric.Value
import fabric.parse.Json
import fabric.rw._
import fabric.filter._
import fs2.Chunk
import org.http4s.headers.`Content-Type`
import org.http4s.{DecodeFailure, EntityDecoder, EntityEncoder, MediaType}

case class FabricEntitySupport(decodeFilter: ValueFilter, encodeFilter: ValueFilter) {
  implicit def decoder[T](implicit writer: Writer[T]): EntityDecoder[IO, T] =
    EntityDecoder.decodeBy(MediaType.application.json) { media =>
      EitherT {
        media.as[String](implicitly[MonadThrow[IO]], EntityDecoder.text).map { jsonString =>
          val json = Json.parse(jsonString).filter(decodeFilter).get
          val t = writer.write(json)
          t.asRight[DecodeFailure]
        }
      }
    }

  implicit def encoder[T](implicit reader: Reader[T]): EntityEncoder[IO, T] = EntityEncoder
    .Pure[Chunk[Byte]]
    .contramap[T] { t =>
      val value = t.toValue.filter(encodeFilter).get
      val string = Json.format(value)
      val bytes = string.getBytes("UTF-8")
      Chunk.array(bytes)
    }.withContentType(`Content-Type`(MediaType.application.json))
}

object FabricEntitySupport extends FabricEntitySupport(NoOpFilter, NoOpFilter)
```

**Comment by rossabaker** [comment]
[transferred the issue now that there's a relevant repo]

The build seems legit.  I'm not sure whether you want to target the development milestones or a stable version of http4s.  (You can do both if you want to maintain branches.)

There should be a license.  The plugin will default to Apache, but it would be good for the repo to make one.

I set up secrets that have rights to publish to http4s.org, and an org secret to take care of the GPG.

I absentmindedly created this repo as private, but just flipped it to public.

**Comment by rossabaker** [comment]
The [blaze build](https://github.com/http4s/blaze/blob/aaa193aed816eb276dfa64cfffa24f99beaf5468/build.sbt) is probably a decent example.  It [pulls in sbt-http4s-org](https://github.com/http4s/blaze/blob/main/project/plugins.sbt#L4), which is based on sbt-typelevel, which is relatively new.  That plugin will create the necessary GitHub YAML for you: you'll just need to run `githubWorkfowGenerate` to materialize it.

Ideally, we'd have a g8 template that sets all this up, but we haven't had that many repos yet (more planned), and the build infra is under very active development.  Sorry, but we're here to help!

**Comment by darkfrog26** [comment]
There seems to be a strange bug in the dependency resolver configuration? https://github.com/http4s/http4s-fabric/runs/5042693182?check_suite_focus=true

**Comment by rossabaker** [comment]
The `v1.0.0` tag is adding `1.0.0` to `mimaPreviousArtifacts`, so it's failing a binary dependency check.  (I would think the plugin should ignore that as being newer.  I'll report an issue there.)  But I also think that's probably an accidental tag, and it will work without it.

**Comment by armanbilge** [comment]
Yes, the "problem" is the `v1.0.0` tag. The real problem is that atm sbt-typelevel can't sort prereleases, but it's been coasting on the assumption that a final is never tagged before a pre-release which isn't the case here. If you can remove the `v1.0.0` tag that should fix things.

Btw you should set `tlBaseVersion := "1.0"`, not the full version number. I just published an FAQ on it: https://typelevel.org/sbt-typelevel/faq.html#what-is-a-base-version-anyway

**Comment by darkfrog26** [comment]
Awesome! Looks like I've got my first release out! Thanks. :)

**Comment by darkfrog26** [comment]
@rossabaker sorry to keep bugging you, but I'm attempting to do a new release for `1.0.0-M31` and it's doing a snapshot release: https://github.com/http4s/http4s-fabric/runs/5159859565?check_suite_focus=true

Do you have any idea why this might be happening?

**Comment by armanbilge** [comment]
@darkfrog26 I haven't looked in detail at your problem but FYI we changed the publishing infrastructure for http4s org, you should update to the latest sbt-http4s-org.
https://github.com/http4s/sbt-http4s-org/releases/tag/v0.12.0

Make sure to run `prePR` in sbt after you update.

**Comment by armanbilge** [comment]
@darkfrog26 the problem is your tag is `v.1.0.0-M31` instead of `v1.0.0-M31`.
https://github.com/http4s/http4s-fabric/releases/tag/v.1.0.0-M31

**Comment by darkfrog26** [comment]
After running `prePR` it sets the default Scala version to 2.12.15, which doesn't work with `1.0.0-M31`. Can we get a new release of the plugin that defaults to 2.13.8 to avoid the build failing in 1.x?

**Comment by armanbilge** [comment]
Actually that default Scala comes from sbt itself :)

You can specify the Scala versions you want like this:
https://github.com/http4s/http4s/blob/4d214acf56facf5288f59eac7c9a47ac083459e2/build.sbt#L9

**Comment by armanbilge** [comment]
You need the `ThisBuild / ` in front of those :)

**Comment by darkfrog26** [comment]
@armanbilge thanks for your patience in the face of stupidity. ;)

**Comment by darkfrog26** [comment]
Argh, it looks like maybe the plugin migrated to s01 but the secrets haven't? https://github.com/http4s/http4s-fabric/runs/5164025607?check_suite_focus=true

**Comment by armanbilge** [comment]
Do you have admin rights on this project? You can remove them in settings, otherwise Ross will have to help with this one.

**Comment by armanbilge** [comment]
Oh, as workaround try setting `ThisBuild / tlSonatypeUseLegacyHost := true`.

**Comment by darkfrog26** [comment]
@armanbilge thanks, that did the trick!

**Comment by armanbilge** [comment]
@darkfrog26 btw if you detest formatting 😉 
https://github.com/typelevel/cats-effect-testing/blob/c100f779b1ed8904cccc99d721ef2eed39a88d59/.scalafmt.conf#L3

**Comment by rossabaker** [comment]
I removed the legacy secrets.  You should inherit the correct ones, and be able to remove that `tlSonatypeUseLegacyHost` moving forward.
